clusters:
  - name: pk2-ppsa01
    apiServer: https://k8s-pk2-ppsa01.example.com:6443
    insecureSkipTlsVerify: false
    caCertBase64: ""
    namespaceSuffixes: [ppsa-central, ppsa-master01, ppsa-master02, ppsa-simple]
  - name: pk5-ppsa01
    apiServer: https://k8s-pk5-ppsa01.example.com:6443
    insecureSkipTlsVerify: false
    caCertBase64: ""
    namespaceSuffixes: [ppsa-central, ppsa-master01, ppsa-master02, ppsa-simple]
